services:
  redfish-exporter:
    build:
      context: .
      platforms:
        - linux/amd64
      #  - linux/aarch64
      dockerfile: Dockerfile
    env_file:
    - .env
    image: quocbao747/redfish-exporter:1.0-beta
    container_name: redfish-exporter
    hostname: redfish-exporter
    domainname: redfish-exporter
    restart: always
    environment:
      TZ: Asia/Ho_Chi_Minh
    platform: linux/amd64
    ports:
      - "9120:9120"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
      replicas: 1